//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.12.29 at 07:37:11 AM CET 
//


package org.dhcpcluster.config.xml.data;

import java.net.InetAddress;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="front-end">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="listen" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" default="67" />
 *                           &lt;attribute name="inet" type="{}inet-address" default="127.0.0.1" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="threads" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="nb" default="2">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 &lt;minInclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="max" default="10">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 &lt;minInclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="core" default="2">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 &lt;minInclusive value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="keepalive" default="10000">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                 &lt;minInclusive value="0"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="global">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="server">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="identifier" use="required" type="{}inet-address" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{}filter" minOccurs="0"/>
 *                   &lt;element ref="{}options" minOccurs="0"/>
 *                   &lt;element name="classes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="class">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;group ref="{}filter-group"/>
 *                                     &lt;attribute name="classid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="topology">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="subnet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}giaddr" maxOccurs="unbounded"/>
 *                             &lt;element name="range">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="start" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="192.168.0.15"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                     &lt;attribute name="end" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;enumeration value="192.168.0.25"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element ref="{}options"/>
 *                             &lt;element ref="{}static" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="address" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="192.168.0.0"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="mask" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="255.255.252.0"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="comment" use="required">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="Free comment!"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "dhcp-server")
public class DhcpServer {

    @XmlElement(name = "front-end", required = true)
    protected DhcpServer.FrontEnd frontEnd;
    @XmlElement(required = true)
    protected DhcpServer.Global global;
    @XmlElement(required = true)
    protected DhcpServer.Topology topology;

    /**
     * Gets the value of the frontEnd property.
     * 
     * @return
     *     possible object is
     *     {@link DhcpServer.FrontEnd }
     *     
     */
    public DhcpServer.FrontEnd getFrontEnd() {
        return frontEnd;
    }

    /**
     * Sets the value of the frontEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DhcpServer.FrontEnd }
     *     
     */
    public void setFrontEnd(DhcpServer.FrontEnd value) {
        this.frontEnd = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link DhcpServer.Global }
     *     
     */
    public DhcpServer.Global getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link DhcpServer.Global }
     *     
     */
    public void setGlobal(DhcpServer.Global value) {
        this.global = value;
    }

    /**
     * Gets the value of the topology property.
     * 
     * @return
     *     possible object is
     *     {@link DhcpServer.Topology }
     *     
     */
    public DhcpServer.Topology getTopology() {
        return topology;
    }

    /**
     * Sets the value of the topology property.
     * 
     * @param value
     *     allowed object is
     *     {@link DhcpServer.Topology }
     *     
     */
    public void setTopology(DhcpServer.Topology value) {
        this.topology = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="listen" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" default="67" />
     *                 &lt;attribute name="inet" type="{}inet-address" default="127.0.0.1" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="threads" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="nb" default="2">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="max" default="10">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="core" default="2">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="keepalive" default="10000">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                       &lt;minInclusive value="0"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "listen",
        "threads"
    })
    public static class FrontEnd {

        protected DhcpServer.FrontEnd.Listen listen;
        protected DhcpServer.FrontEnd.Threads threads;

        /**
         * Gets the value of the listen property.
         * 
         * @return
         *     possible object is
         *     {@link DhcpServer.FrontEnd.Listen }
         *     
         */
        public DhcpServer.FrontEnd.Listen getListen() {
            return listen;
        }

        /**
         * Sets the value of the listen property.
         * 
         * @param value
         *     allowed object is
         *     {@link DhcpServer.FrontEnd.Listen }
         *     
         */
        public void setListen(DhcpServer.FrontEnd.Listen value) {
            this.listen = value;
        }

        /**
         * Gets the value of the threads property.
         * 
         * @return
         *     possible object is
         *     {@link DhcpServer.FrontEnd.Threads }
         *     
         */
        public DhcpServer.FrontEnd.Threads getThreads() {
            return threads;
        }

        /**
         * Sets the value of the threads property.
         * 
         * @param value
         *     allowed object is
         *     {@link DhcpServer.FrontEnd.Threads }
         *     
         */
        public void setThreads(DhcpServer.FrontEnd.Threads value) {
            this.threads = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" default="67" />
         *       &lt;attribute name="inet" type="{}inet-address" default="127.0.0.1" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Listen {

            @XmlAttribute
            @XmlSchemaType(name = "unsignedShort")
            protected Integer port;
            @XmlAttribute
            @XmlJavaTypeAdapter(Adapter3 .class)
            protected InetAddress inet;

            /**
             * Gets the value of the port property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getPort() {
                if (port == null) {
                    return  67;
                } else {
                    return port;
                }
            }

            /**
             * Sets the value of the port property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPort(Integer value) {
                this.port = value;
            }

            /**
             * Gets the value of the inet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public InetAddress getInet() {
                if (inet == null) {
                    return new Adapter3().unmarshal("127.0.0.1");
                } else {
                    return inet;
                }
            }

            /**
             * Sets the value of the inet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInet(InetAddress value) {
                this.inet = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="nb" default="2">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="max" default="10">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="core" default="2">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="keepalive" default="10000">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *             &lt;minInclusive value="0"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Threads {

            @XmlAttribute
            protected Integer nb;
            @XmlAttribute
            protected Integer max;
            @XmlAttribute
            protected Integer core;
            @XmlAttribute
            protected Integer keepalive;

            /**
             * Gets the value of the nb property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getNb() {
                if (nb == null) {
                    return  2;
                } else {
                    return nb;
                }
            }

            /**
             * Sets the value of the nb property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNb(Integer value) {
                this.nb = value;
            }

            /**
             * Gets the value of the max property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getMax() {
                if (max == null) {
                    return  10;
                } else {
                    return max;
                }
            }

            /**
             * Sets the value of the max property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setMax(Integer value) {
                this.max = value;
            }

            /**
             * Gets the value of the core property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getCore() {
                if (core == null) {
                    return  2;
                } else {
                    return core;
                }
            }

            /**
             * Sets the value of the core property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCore(Integer value) {
                this.core = value;
            }

            /**
             * Gets the value of the keepalive property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public int getKeepalive() {
                if (keepalive == null) {
                    return  10000;
                } else {
                    return keepalive;
                }
            }

            /**
             * Sets the value of the keepalive property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setKeepalive(Integer value) {
                this.keepalive = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="server">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="identifier" use="required" type="{}inet-address" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{}filter" minOccurs="0"/>
     *         &lt;element ref="{}options" minOccurs="0"/>
     *         &lt;element name="classes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="class">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;group ref="{}filter-group"/>
     *                           &lt;attribute name="classid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "server",
        "filter",
        "options",
        "classes"
    })
    public static class Global {

        @XmlElement(required = true)
        protected DhcpServer.Global.Server server;
        protected Filter filter;
        protected Options options;
        protected DhcpServer.Global.Classes classes;

        /**
         * Gets the value of the server property.
         * 
         * @return
         *     possible object is
         *     {@link DhcpServer.Global.Server }
         *     
         */
        public DhcpServer.Global.Server getServer() {
            return server;
        }

        /**
         * Sets the value of the server property.
         * 
         * @param value
         *     allowed object is
         *     {@link DhcpServer.Global.Server }
         *     
         */
        public void setServer(DhcpServer.Global.Server value) {
            this.server = value;
        }

        /**
         * Gets the value of the filter property.
         * 
         * @return
         *     possible object is
         *     {@link Filter }
         *     
         */
        public Filter getFilter() {
            return filter;
        }

        /**
         * Sets the value of the filter property.
         * 
         * @param value
         *     allowed object is
         *     {@link Filter }
         *     
         */
        public void setFilter(Filter value) {
            this.filter = value;
        }

        /**
         * Gets the value of the options property.
         * 
         * @return
         *     possible object is
         *     {@link Options }
         *     
         */
        public Options getOptions() {
            return options;
        }

        /**
         * Sets the value of the options property.
         * 
         * @param value
         *     allowed object is
         *     {@link Options }
         *     
         */
        public void setOptions(Options value) {
            this.options = value;
        }

        /**
         * Gets the value of the classes property.
         * 
         * @return
         *     possible object is
         *     {@link DhcpServer.Global.Classes }
         *     
         */
        public DhcpServer.Global.Classes getClasses() {
            return classes;
        }

        /**
         * Sets the value of the classes property.
         * 
         * @param value
         *     allowed object is
         *     {@link DhcpServer.Global.Classes }
         *     
         */
        public void setClasses(DhcpServer.Global.Classes value) {
            this.classes = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="class">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;group ref="{}filter-group"/>
         *                 &lt;attribute name="classid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clazz"
        })
        public static class Classes {

            @XmlElement(name = "class")
            protected List<DhcpServer.Global.Classes.Class> clazz;

            /**
             * Gets the value of the clazz property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the clazz property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getClazz().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DhcpServer.Global.Classes.Class }
             * 
             * 
             */
            public List<DhcpServer.Global.Classes.Class> getClazz() {
                if (clazz == null) {
                    clazz = new ArrayList<DhcpServer.Global.Classes.Class>();
                }
                return this.clazz;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;group ref="{}filter-group"/>
             *       &lt;attribute name="classid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "filterGroup"
            })
            public static class Class {

                @XmlElements({
                    @XmlElement(name = "filter-always-true", type = Filter.FilterAlwaysTrue.class),
                    @XmlElement(name = "filter-num-option", type = Filter.FilterNumOption.class),
                    @XmlElement(name = "filter-and", type = Filter.FilterAnd.class),
                    @XmlElement(name = "filter-string-option", type = Filter.FilterStringOption.class),
                    @XmlElement(name = "filter-not", type = Filter.FilterNot.class),
                    @XmlElement(name = "filter-or", type = Filter.FilterOr.class),
                    @XmlElement(name = "filter-always-false", type = Filter.FilterAlwaysFalse.class)
                })
                protected TypeFilterRoot filterGroup;
                @XmlAttribute(required = true)
                protected String classid;

                /**
                 * Gets the value of the filterGroup property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Filter.FilterAlwaysTrue }
                 *     {@link Filter.FilterNumOption }
                 *     {@link Filter.FilterAnd }
                 *     {@link Filter.FilterStringOption }
                 *     {@link Filter.FilterNot }
                 *     {@link Filter.FilterOr }
                 *     {@link Filter.FilterAlwaysFalse }
                 *     
                 */
                public TypeFilterRoot getFilterGroup() {
                    return filterGroup;
                }

                /**
                 * Sets the value of the filterGroup property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Filter.FilterAlwaysTrue }
                 *     {@link Filter.FilterNumOption }
                 *     {@link Filter.FilterAnd }
                 *     {@link Filter.FilterStringOption }
                 *     {@link Filter.FilterNot }
                 *     {@link Filter.FilterOr }
                 *     {@link Filter.FilterAlwaysFalse }
                 *     
                 */
                public void setFilterGroup(TypeFilterRoot value) {
                    this.filterGroup = value;
                }

                /**
                 * Gets the value of the classid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getClassid() {
                    return classid;
                }

                /**
                 * Sets the value of the classid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setClassid(String value) {
                    this.classid = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="identifier" use="required" type="{}inet-address" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Server {

            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(Adapter3 .class)
            protected InetAddress identifier;

            /**
             * Gets the value of the identifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public InetAddress getIdentifier() {
                return identifier;
            }

            /**
             * Sets the value of the identifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentifier(InetAddress value) {
                this.identifier = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="subnet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}giaddr" maxOccurs="unbounded"/>
     *                   &lt;element name="range">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="start" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="192.168.0.15"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="end" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;enumeration value="192.168.0.25"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element ref="{}options"/>
     *                   &lt;element ref="{}static" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="address" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="192.168.0.0"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="mask" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="255.255.252.0"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="comment" use="required">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="Free comment!"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subnet"
    })
    public static class Topology {

        @XmlElement(required = true)
        protected DhcpServer.Topology.Subnet subnet;

        /**
         * Gets the value of the subnet property.
         * 
         * @return
         *     possible object is
         *     {@link DhcpServer.Topology.Subnet }
         *     
         */
        public DhcpServer.Topology.Subnet getSubnet() {
            return subnet;
        }

        /**
         * Sets the value of the subnet property.
         * 
         * @param value
         *     allowed object is
         *     {@link DhcpServer.Topology.Subnet }
         *     
         */
        public void setSubnet(DhcpServer.Topology.Subnet value) {
            this.subnet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}giaddr" maxOccurs="unbounded"/>
         *         &lt;element name="range">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="start" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="192.168.0.15"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="end" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;enumeration value="192.168.0.25"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element ref="{}options"/>
         *         &lt;element ref="{}static" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="address" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="192.168.0.0"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="mask" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="255.255.252.0"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="comment" use="required">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="Free comment!"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "giaddr",
            "range",
            "options",
            "_static"
        })
        public static class Subnet {

            @XmlElement(required = true)
            protected List<String> giaddr;
            @XmlElement(required = true)
            protected DhcpServer.Topology.Subnet.Range range;
            @XmlElement(required = true)
            protected Options options;
            @XmlElement(name = "static", required = true)
            protected List<Static> _static;
            @XmlAttribute(required = true)
            protected String address;
            @XmlAttribute(required = true)
            protected String mask;
            @XmlAttribute(required = true)
            protected String comment;

            /**
             * Gets the value of the giaddr property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the giaddr property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGiaddr().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getGiaddr() {
                if (giaddr == null) {
                    giaddr = new ArrayList<String>();
                }
                return this.giaddr;
            }

            /**
             * Gets the value of the range property.
             * 
             * @return
             *     possible object is
             *     {@link DhcpServer.Topology.Subnet.Range }
             *     
             */
            public DhcpServer.Topology.Subnet.Range getRange() {
                return range;
            }

            /**
             * Sets the value of the range property.
             * 
             * @param value
             *     allowed object is
             *     {@link DhcpServer.Topology.Subnet.Range }
             *     
             */
            public void setRange(DhcpServer.Topology.Subnet.Range value) {
                this.range = value;
            }

            /**
             * Gets the value of the options property.
             * 
             * @return
             *     possible object is
             *     {@link Options }
             *     
             */
            public Options getOptions() {
                return options;
            }

            /**
             * Sets the value of the options property.
             * 
             * @param value
             *     allowed object is
             *     {@link Options }
             *     
             */
            public void setOptions(Options value) {
                this.options = value;
            }

            /**
             * Gets the value of the static property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the static property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getStatic().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Static }
             * 
             * 
             */
            public List<Static> getStatic() {
                if (_static == null) {
                    _static = new ArrayList<Static>();
                }
                return this._static;
            }

            /**
             * Gets the value of the address property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddress() {
                return address;
            }

            /**
             * Sets the value of the address property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddress(String value) {
                this.address = value;
            }

            /**
             * Gets the value of the mask property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMask() {
                return mask;
            }

            /**
             * Sets the value of the mask property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMask(String value) {
                this.mask = value;
            }

            /**
             * Gets the value of the comment property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getComment() {
                return comment;
            }

            /**
             * Sets the value of the comment property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setComment(String value) {
                this.comment = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="start" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="192.168.0.15"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="end" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;enumeration value="192.168.0.25"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Range {

                @XmlAttribute(required = true)
                protected String start;
                @XmlAttribute(required = true)
                protected String end;

                /**
                 * Gets the value of the start property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStart() {
                    return start;
                }

                /**
                 * Sets the value of the start property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStart(String value) {
                    this.start = value;
                }

                /**
                 * Gets the value of the end property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEnd() {
                    return end;
                }

                /**
                 * Sets the value of the end property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEnd(String value) {
                    this.end = value;
                }

            }

        }

    }

}
