//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.30 at 02:05:11 PM CEST 
//


package org.dhcpcluster.config.xml.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for type-subnet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="type-subnet">
 *   &lt;complexContent>
 *     &lt;extension base="{}type-node-subnet">
 *       &lt;all>
 *         &lt;element name="policy" type="{}policyType" minOccurs="0"/>
 *         &lt;element ref="{}giaddrs" minOccurs="0"/>
 *         &lt;element ref="{}pools" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type-subnet", propOrder = {
    "policy",
    "giaddrs",
    "pools"
})
@XmlSeeAlso({
    Subnet.class
})
public class TypeSubnet
    extends TypeNodeSubnet
{

    protected PolicyType policy;
    protected Giaddrs giaddrs;
    protected Pools pools;

    /**
     * Gets the value of the policy property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyType }
     *     
     */
    public PolicyType getPolicy() {
        return policy;
    }

    /**
     * Sets the value of the policy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyType }
     *     
     */
    public void setPolicy(PolicyType value) {
        this.policy = value;
    }

    /**
     * Gets the value of the giaddrs property.
     * 
     * @return
     *     possible object is
     *     {@link Giaddrs }
     *     
     */
    public Giaddrs getGiaddrs() {
        return giaddrs;
    }

    /**
     * Sets the value of the giaddrs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Giaddrs }
     *     
     */
    public void setGiaddrs(Giaddrs value) {
        this.giaddrs = value;
    }

    /**
     * Gets the value of the pools property.
     * 
     * @return
     *     possible object is
     *     {@link Pools }
     *     
     */
    public Pools getPools() {
        return pools;
    }

    /**
     * Sets the value of the pools property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pools }
     *     
     */
    public void setPools(Pools value) {
        this.pools = value;
    }

}
