//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.27 at 10:21:47 AM CEST 
//


package org.dhcpcluster.config.xml.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for type-option-int complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="type-option-int">
 *   &lt;complexContent>
 *     &lt;extension base="{}option-generic">
 *       &lt;sequence>
 *         &lt;element ref="{}value-int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "type-option-int", propOrder = {
    "valueInt"
})
public class TypeOptionInt
    extends OptionGeneric
{

    @XmlElement(name = "value-int")
    protected int valueInt;

    /**
     * Gets the value of the valueInt property.
     * 
     */
    public int getValueInt() {
        return valueInt;
    }

    /**
     * Sets the value of the valueInt property.
     * 
     */
    public void setValueInt(int value) {
        this.valueInt = value;
    }

}
